<a href="https://colab.research.google.com/github/sanketingole/MachineLearning_Practice/blob/main/Cars24_LinearRegression_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
!gdown 1bwRmKkPwmLKiqOgQ_LnKH0Vsc3mJKmVR

Downloading...
From: https://drive.google.com/uc?id=1bwRmKkPwmLKiqOgQ_LnKH0Vsc3mJKmVR
To: /content/cars24-car-price-cleaned.csv
100% 1.69M/1.69M [00:00<00:00, 15.4MB/s]

In [3]:
df = pd.read_csv('cars24-car-price-cleaned.csv')
df.head()

,selling_price,year,km_driven,mileage,engine,max_power,age,make,model,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
0,1.20,2012.0,120000,19.70,796.0,46.30,11.0,MARUTI,ALTO STD,1,0,0,0,0,1,1,1,0
1,5.50,2016.0,20000,18.90,1197.0,82.00,7.0,HYUNDAI,GRAND I10 ASTA,1,0,0,0,0,1,1,1,0
2,2.15,2010.0,60000,17.00,1197.0,80.00,13.0,HYUNDAI,I20 ASTA,1,0,0,0,0,1,1,1,0
3,2.26,2012.0,37000,20.92,998.0,67.10,11.0,MARUTI,ALTO K10 2010-2014 VXI,1,0,0,0,0,1,1,1,0
4,5.70,2015.0,30000,22.77,1498.0,98.59,8.0,FORD,ECOSPORT 2015-2021 1.5 TDCI TITANIUM BSIV,0,0,1,0,0,0,1,1,0

In [4]:
df['make'].nunique()

41

In [5]:
df['make'].value_counts()

make
MARUTI           5650
HYUNDAI          3562
HONDA            1779
MAHINDRA         1276
TOYOTA           1189
TATA              971
FORD              900
VOLKSWAGEN        761
RENAULT           636
MERCEDES-BENZ     485
BMW               483
SKODA             422
CHEVROLET         406
AUDI              324
NISSAN            289
DATSUN            170
FIAT              113
JAGUAR             80
LAND               51
VOLVO              42
JEEP               41
MITSUBISHI         39
KIA                33
PORSCHE            25
MINI               23
MG                 19
ISUZU              12
LEXUS              10
FORCE               5
AMBASSADOR          4
BENTLEY             4
OPELCORSA           3
DAEWOO              2
MASERATI            2
PREMIER             2
DC                  2
LAMBORGHINI         1
FERRARI             1
MERCEDES-AMG        1
ROLLS-ROYCE         1
OPEL                1
Name: count, dtype: int64

In [8]:
## Percentange
df['make'].value_counts(normalize=True)

make
MARUTI           0.285066
HYUNDAI          0.179717
HONDA            0.089758
MAHINDRA         0.064379
TOYOTA           0.059990
TATA             0.048991
FORD             0.045409
VOLKSWAGEN       0.038396
RENAULT          0.032089
MERCEDES-BENZ    0.024470
BMW              0.024369
SKODA            0.021292
CHEVROLET        0.020484
AUDI             0.016347
NISSAN           0.014581
DATSUN           0.008577
FIAT             0.005701
JAGUAR           0.004036
LAND             0.002573
VOLVO            0.002119
JEEP             0.002069
MITSUBISHI       0.001968
KIA              0.001665
PORSCHE          0.001261
MINI             0.001160
MG               0.000959
ISUZU            0.000605
LEXUS            0.000505
FORCE            0.000252
AMBASSADOR       0.000202
BENTLEY          0.000202
OPELCORSA        0.000151
DAEWOO           0.000101
MASERATI         0.000101
PREMIER          0.000101
DC               0.000101
LAMBORGHINI      0.000050
FERRARI          0.000050
MERCEDES-AMG     0.000050
ROLLS-ROYCE      0.000050
OPEL             0.000050
Name: proportion, dtype: float64

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_new = pd.DataFrame(scaler.fit_transform(df.iloc[:,1:5]), columns=df.columns[1:5])
df_new.head()

       year  km_driven   mileage    engine
0  0.689655   0.031553  0.135345  0.117891
1  0.827586   0.005237  0.128448  0.177281
2  0.620690   0.015764  0.112069  0.177281
3  0.689655   0.009711  0.145862  0.147808
4  0.793103   0.007869  0.161810  0.221860

**train test split**

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
df.head()

,selling_price,year,km_driven,mileage,engine,max_power,age,make,model,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
0,1.20,2012.0,120000,19.70,796.0,46.30,11.0,MARUTI,ALTO STD,1,0,0,0,0,1,1,1,0
1,5.50,2016.0,20000,18.90,1197.0,82.00,7.0,HYUNDAI,GRAND I10 ASTA,1,0,0,0,0,1,1,1,0
2,2.15,2010.0,60000,17.00,1197.0,80.00,13.0,HYUNDAI,I20 ASTA,1,0,0,0,0,1,1,1,0
3,2.26,2012.0,37000,20.92,998.0,67.10,11.0,MARUTI,ALTO K10 2010-2014 VXI,1,0,0,0,0,1,1,1,0
4,5.70,2015.0,30000,22.77,1498.0,98.59,8.0,FORD,ECOSPORT 2015-2021 1.5 TDCI TITANIUM BSIV,0,0,1,0,0,0,1,1,0

In [13]:
y = df['selling_price']
X = df.drop('selling_price', axis=1)
print(y.shape,X.shape)

(19820,) (19820, 17)

In [15]:
X_train, X_test, y_train, y_test =  train_test_split(X,y, test_size=0.3 , random_state = 3)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(13874, 17) (5946, 17) (13874,) (5946,)

In [16]:
X_train.head()

,year,km_driven,mileage,engine,max_power,age,make,model,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
11625,2019.0,23000,16.55,2498.0,105.00,4.0,MAHINDRA,THAR 700 CRDE ABS,1,0,1,0,0,0,1,0,1
4115,2019.0,12705,21.01,1197.0,81.80,4.0,MARUTI,BALENO ALPHA,0,0,0,0,0,1,1,1,0
15960,2017.0,40000,17.57,1193.0,88.70,6.0,TATA,ZEST REVOTRON 1.2 XT,1,0,0,0,0,1,1,1,0
14730,2014.0,70000,22.32,1582.0,126.32,9.0,HYUNDAI,VERNA 1.6 SX,0,0,1,0,0,0,1,1,0
7835,2016.0,45000,21.40,1197.0,83.10,7.0,MARUTI,BALENO DELTA 1.2,0,0,0,0,0,1,1,1,0